---
title: "shinytesti"
author: "hruoho"
date: "20.03.2015"
output:
  html_document:
    number_sections: yes
runtime: shiny
---

##Tuntitehtävät

### 
Sijoitat kahden vuoden määräaikaistilille 3 000 €. Tilin vuotuinen korko on 1.2 \% ja sijoitusajan lopussa maksettava lisäkorko 5 \%. Mikä oli sijoituksen nettokorkotuotto prosentteina? 

`r k <- 3000; n <- 2; i <- 0.012; j <- 0.05;`
    Korkojen jälkeen rahaa on $3000\cdot(`r 1 + i`)^{`r n`}\cdot(`r 1+j`) = `r K <- (1+i)*(1+j)**n*k; K`$ euroa, joten nettokorkotuotto on `r K-k` euroa.

###
Korkeakorkoiselle tilille talletettiin rahasumma neljäksi vuodeksi. Tilin vuotuinen korkokanta oli 3.5 \% ja talletusajan lopussa alkuperäiselle pääomalle maksettiin 7.5 \% lisäkorko. Kuinka suuri oli alkuperäinen talletus, jos talletusajan päätyttyä tililtä nostettiin 10387.45 euroa?
```{r, echo = FALSE}
#talletusaika
n <- 4
#vuotuinen korkokanta
i <- 0.035
#lisäkorko
l <- 0.075
#lopullinen pääoma
K <- 112500.34
#ilman kymmenen potensseja
fK <- format(K, scientific = FALSE)
```
    Jos $k$ on alkuperäinen pääoma, niin 
$$
  k\cdot(`r 1+i`)^{`r n`}\cdot(`r 1+l`) = `r fK`
$$
josta saadaan
$$
  k = \frac{`r fK`}{(`r 1+i`)^{`r n`}\cdot(`r 1+l`)} = `r vastaus <- format(round(K/(1+i)**n*(1+l), 2), scientific=FALSE); vastaus`  
$$
Siis $k = `r vastaus`$ euroa.

1. Selvitä kurssimateriaalista, miten sijoitusvakuutusta verotetaan. 

1. Sijoitat sijoitusvakuutukseen vuoden alussa 1 500 € \ ja kahden seuraavan vuoden alussa 1 000 €  vuosittain. Vakuutuksesta pitää maksaa sijoitettavan summan lisäksi hoitokuluja 15 euroa vuodessa. Sijoitusvakuutuksen vuosituotoksi arvioidaan 6 \%. Mikä on sijoituksesi nettotuotto kolmen vuoden kuluttua? 
`r menot <- 1500 + 2*1000 + 3*15; sij <- c(1500,1000,1000); q <- 1+0.06;  tulot <- q*sij[3]+q**2*sij[2]+q**3*sij[1]; vastaus <- 0.7*(tulot - menot); vastaus`
  
1. Isotätisi tallettaa sijoitusvakuutukseen ensimmäisenä vuonna 3 000 euroa ja toisena vuonna 2 000 euroa. Hän maksoi vakuutuksesta sijoitettavan summan lisäksi hoitokuluja 20 euroa vuodessa. Sijoitusvakuutuksen vuosituotto oli ensimmäisenä vuonna 7 \% ja toisena vuonna 4 \%. Edunsaajaksi isotätisi määräsi sinut. Kuinka paljon rahaa sait vakuutuksesta verojen maksamisen jälkeen?
`r talletukset <- c(3000,2000); tuotot <- c(1.07,1.04); brutto <- prod(tuotot)*3000 + tuotot[2]*2000; tuotto <- brutto - sum(talletukset)-2*20; nettotuotto <- 0.7*tuotto; lahja <- sum(talletukset); nettolahja <- lahja-(100 + 0.2*(lahja - 4000)); nettotuotto + nettolahja`

1. 
    a. Selvitä kurssimateriaalista, mitä tarkoittavat seuraavat käsitteet:     
        - joukkovelkakirjalaina
        - obligaatio
        - liikkeellelaskupäivä
        - nimellisarvo
        - emissiokurssi
        - jälkimarkkinahyvitys 
        
    a. Selviä kurssimateriaalista, miten obligaatioiden tuottoa verotetaan. 
  

1. Kaverisi osti nimellisarvoltaan 2 000 eurolla obligaatioita 95 \% emissiokurssilla 73 päivää lainan liikkeellelaskun jälkeen. Obligaatioiden korkokanta oli 4.8 \% p.a. ja laina-aika kymmenen vuotta. Korkopäivien laskemiseen käytettiin tapaa todelliset/365.
    a. Kuinka paljon kaverisi maksoi obligaatioistaan yhteensä?
    a. Kuinka paljon kaverisi sai sijoituksestaan nettotuottoa, jos hän myi obligaatiot viiden vuoden kuluttua liikkeellelaskupäivästä hintaan 2 200 euroa?

1. Valtion liikkeellelaskeman obligaatiolainan vuosikorko oli 5 \%. Sijoittaja osti kolme obligaatiota 108 päivää liikkeellelaskun jälkeen, kun emissiokurssi oli 102 \%. Mikä oli yhden obligaation nimellisarvo, jos sijoittaja maksoi obligaatioista yhteensä 4 657.50 euroa? Käytä korkopäivien laskemiseen tapaa todelliset/360.

1. Selvitä kurssimateriaalista, mitä tarkoittavat käsitteet osake ja osinko.

1. Selviä kurssimateriaalista, miten pörssiin listattujen yhtiöiden osakkeiden tuottoa verotetaan.
 
1. Kaverisi osti 600 kappaletta erään pörssiin listatun yrityksen osakkeita 9.45 euron kappalehintaan. Keväällä yritys jakoi jokaiselta osakkeelta osinkoa 1.15 €. Vuoden lopulla kaverisi myi osakkeet 10.90 euron kappalehintaan. Sekä oston että myynnin yhteydessä perittiin välityspalkkiota 1.0 \% kauppahinnasta. Mikä oli kaverisi sijoituksen nettotuotto?

1. Sijoittaja osti 90 kappaletta erään yhtiön osakkeita kurssilla 35.86 €. Yhdeksän kuukauden kuluttua hän myi osakkeet kurssilla 37.23 €. Välityspalkkio oli sekä ostettaessa että myytäessä $0.25\ \%  + 7.50€$. Mikä oli sijoituksen nettotuottoa vastaava vuosittainen korkokanta?

1. Selviä kurssimateriaalista, miten sijoitusrahastojen tuottoa verotetaan.

1. Kaverisi osti korkorahaston osuuksia 1 200 eurolla. Hän myi osuudet vuoden kuluttua, jolloin osuuksien arvo oli 1 350 euroa. Kauppojen yhteydessä perityt välityspalkkiot olivat sekä oston että myynnin tapauksessa 0.95 \% kauppahinnasta. Mikä oli sijoituksen nettotuottoa vastaava vuosittainen korkokanta?

1. Sijoitit rahastoon 95 € \  ja sait 8.5 rahasto-osuutta. Kahden kuukauden kuluttua rahasto-osuuden arvo oli noussut 3.2 \%. Kuinka monta rahasto-osuutta sait, jos sijoitit saman summan kuin edellisellä kerralla?

1. Sijoitat loppuvuoden aikana erääseen rahastoon joka kuukausi saman summan syyskuusta alkaen. Rahasto-osuuden arvo euroina on alla olevassa taulukossa. Oletko voitolla vai tappiolla sijoituksissasi joulukuun sijoituksen jälkeen? Kuinka monta prosenttia voitto tai tappio on kokonaissijoituksestasi?

1. Kaverisi tallettaa 16.4.2014 määräaikaistilille 2 400 euroa. Tilin eräpäiväksi asetetaan 20.3.2015. Tilin kiinteä korko on 2.95 \% p.a. ja se lasketaan korkotavan todelliset/360 mukaan. Korko liitetään pääomaan vuoden vaihteessa ja talletuksen eräpäivänä. Kuinka paljon kaverisi voi nostaa tililtään eräpäivänä?

1. Ostat 50 kappaletta erään yrityksen osakkeita hintaan 21.75 €/kpl. Välityspalkkio on 0.5~\% kauppahinnasta, kuitenkin vähintään 8 €. Kuinka paljon maksat yhdestä osakkeesta, jos välityspalkkio otetaan huomioon?

1. Joukkovelkakirjalainan korkokanta on 5.5 \% p.a. ja laina-aika kolme vuotta. Ostat tämän lainan obligaatioita 144 päivää liikkeellelaskun jälkeen, kun emissiokurssi on 98.5 \%. Ostamiesi obligaatioiden nimellisarvo on yhteensä 2 500 euroa. Jos olisit tallettanut obligaatioista maksamasi summan pankkitilille, mikä olisi sen vuotuisen korkokannan pitänyt olla, jotta sijoitusten nettotuotot olisivat yhtä suuria? Korkotapana 30/360.

1. Talletat sijoitusvakuutukseen kolmena peräkkäisenä vuonna jokaisen vuoden alussa 2 000 euroa. Sijoitusvakuutuksen vuotuinen tuotto on ensimmäisenä vuonna 3 \%, toisena vuonna 2 \% ja kolmantena vuonna 2.5 \%. Maksat sijoittamiesi rahasummien lisäksi vakuutuksesta hoitomaksua 15 € \ vuodessa. 

1. Mikä on sijoituksesi nettotuotto sijoitusajan päättyessä kolmannen vuoden lopussa? 

1. Jos olisit tallettanut sijoittamasi summat samalla tavalla vuosittain pankkitilille, jonka korkokanta on 2.5 \% p.a., olisiko nettotuotto ollut suurempi vai pienempi kuin sijoitusvakuutuksessa?
